name: terraformcode

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        run: az login --service-principal --username 54d39da4-5fac-445e-beed-05fb8cc68cab --password "cbY8Q~K4Y32L1efm15aG5Xj30_2zI0Fks6SWjc12" --tenant 769f02f0-a8ac-43dd-84c2-aec6b69e0ca3
      #     az login --service-principal \
      #     --username ${{ secrets.AZURE_CLIENT_ID }} \
      #     --password ${{ secrets.AZURE_CLIENT_SECRET }} \
      #     --tenant ${{ secrets.AZURE_TENANT_ID }}
       az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: Set Subscription
      #   run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terrafor Init
        run: terraform init
