
name: terraformcode
on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        run: az login --service-principal --username 54d39da4-5fac-445e-beed-05fb8cc68cab --password "cbY8Q~K4Y32L1efm15aG5Xj30_2zI0Fks6SWjc12" --tenant 769f02f0-a8ac-43dd-84c2-aec6b69e0ca3
       
        
      
      - name: terraform init
        run: terraform init
