name: terraformcode

on:
 workflow_dispatch:
 push:
  branches:
  - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Azure login
        run: az login --service-principal --username 54d39da4-5fac-445e-beed-05fb8cc68cab --password "cbY8Q~K4Y32L1efm15aG5Xj30_2zI0Fks6SWjc12" --tenant 769f02f0-a8ac-43dd-84c2-aec6b69e0ca3

      - name: Terrafor Init
        run: terraform init
      
      - name: Terrafor Plan
        run: terraform plan 
      
      - name: Terrafor apply
        run: terraform apply -auto-approve  
